name: Publish

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Sanity check package contents
        run: npm pack --dry-run

      - name: Skip if version already published
        id: check
        run: |
          PKG=$(node -p "require('./package.json').name")
          VER=$(node -p "require('./package.json').version")
          PUB=$(npm view "$PKG" version || echo "0.0.0")
          echo "local=$VER published=$PUB"
          if [ "$VER" = "$PUB" ]; then echo "skip=true" >> $GITHUB_OUTPUT; fi

      - name: Publish package
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && steps.check.outputs.skip != 'true' }}
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}